/* Key knowledge, VCE Economics Units 3 & 4, in study design order.
   Generated from the study design. 71 items.
   If VCAA reorders the key knowledge, these codes change meaning —
   diff this file against the new study design before reusing stored data. */

const KK_DATA = {
  "3.1.1": "the concept of relative scarcity, including needs, wants, resources, opportunity cost and the production possibility frontier (PPF) model, and the three basic economic questions",
  "3.1.2": "the meaning and significance of economic efficiency, including allocative efficiency, productive efficiency, dynamic efficiency and intertemporal efficiency and their relationship to the PPF model",
  "3.1.3": "the conditions for a free and perfectly competitive market",
  "3.1.4": "the law of demand and the theory of the law of demand, including the income effect and the substitution effect",
  "3.1.5": "the demand curve, including movements along and shifts of the demand curve",
  "3.1.6": "non-price factors likely to affect demand and the position of the demand curve, including changes in disposable income, the prices of substitutes and complements, preferences and tastes, interest rates, population demographics and consumer confidence",
  "3.1.7": "the law of supply and the theory of the law of supply, including the profit motive",
  "3.1.8": "the supply curve, including movements along and shifts of the supply curve",
  "3.1.9": "non-price factors likely to affect supply and the position of the supply curve, including changes in the costs of production, number of suppliers, technology, productivity and climatic conditions",
  "3.1.10": "the effects of changes in supply and demand on equilibrium prices and quantity traded",
  "3.1.11": "the meaning and significance of price elasticity of demand and supply",
  "3.1.12": "factors affecting price elasticity of demand, including degree of necessity, availability of substitutes, proportion of income and time",
  "3.1.13": "factors affecting price elasticity of supply, including spare capacity, production period and durability of goods",
  "3.1.14": "the role of relative prices in the allocation of resources",
  "3.1.15": "the role of free and competitive markets in promoting an efficient allocation of resources and improved living standards",
  "3.1.16": "types of market failure, including public goods, externalities, asymmetric information and common access resources",
  "3.1.17": "the role and effect of indirect taxation, subsidies, regulations, advertising and direct provision as forms of government intervention in the market to address market failure",
  "3.1.18": "one example of a government intervention in markets that unintentionally leads to a decrease in one of allocative, productive, dynamic or intertemporal efficiency",
  "3.2.1": "the difference between material and non-material living standards and factors that may affect living standards, including access to goods and services, environmental quality, physical and mental health, crime rates and literacy rates",
  "3.2.2": "the five-sector circular flow model of income, including the role of households, businesses, government, financial institutions and the external sector in an open contemporary macroeconomy",
  "3.2.3": "the business cycle and its causes",
  "3.2.4": "the meaning and importance of aggregate demand and the factors that may affect the level of aggregate demand in the economy, including disposable income, interest rates, consumer confidence, business confidence, the exchange rate and rates of economic growth overseas",
  "3.2.5": "the meaning and importance of aggregate supply and the factors that may affect the level of aggregate supply in the economy, including quantity and quality of the factors of production, costs of production, technological change, productivity growth, exchange rates and climatic conditions, and other events including government regulations and disruptions to international supply chains",
  "3.2.6": "the meaning of the goal of strong and sustainable economic growth",
  "3.2.7": "measurement of the rate of economic growth using growth in real Gross Domestic Product (GDP)",
  "3.2.8": "consequences of not achieving the goal of strong and sustainable economic growth and its effect on living standards, including environmental degradation, external pressures, high inflation if growth is too high, and high unemployment if growth is too low",
  "3.2.9": "the meaning of the goal of full employment, including the NAIRU (natural rate of unemployment)",
  "3.2.10": "classifications within the labour force, including employed, unemployed, hidden unemployed, long-term unemployed, underemployed and frictional unemployment",
  "3.2.11": "measurement of the labour force, including the participation rate, the unemployment rate and the labour force under-utilisation rate",
  "3.2.12": "the difference between cyclical and structural unemployment",
  "3.2.13": "the consequences of not achieving the goal of full employment and its effect on living standards, including the impact on GDP and tax revenue if unemployment is too high and the effects on inflation if unemployment is too low",
  "3.2.14": "the meaning of the goal of low and stable inflation (price stability)",
  "3.2.15": "the distinction between inflation, disinflation and deflation",
  "3.2.16": "measurement of the inflation rate using the Consumer Price Index (CPI), including the difference between the headline and underlying (core) rate of inflation",
  "3.2.17": "causes of inflation, including demand inflation and cost inflation",
  "3.2.18": "consequences of not achieving the goal of low and stable inflation (price stability) and its effect on living standards, including erosion of purchasing power, development of a wage-price spiral, distortion of spending and investment decisions, lower returns on investment, loss of international competitiveness if it is too high, and delayed consumption and unemployment if it is too low",
  "3.2.19": "aggregate demand and aggregate supply factors that have affected the level of achievement or non- achievement of the goals of strong and sustainable economic growth, full employment and low and stable inflation over the past two years",
  "3.3.1": "the gains from international trade, including lower prices, greater choice, access to resources, economies of scale, and increased competition and efficiency",
  "3.3.2": "the balance of payments and its components",
  "3.3.3": "cyclical and structural influences on Australia’s current account balance",
  "3.3.4": "the composition and cause of net foreign debt and net foreign equities",
  "3.3.5": "the exchange rate, its meaning and measurement and the factors affecting its value, including relative interest rates, commodity prices and the terms of trade, demand for exports and imports, foreign investment, relative rates of inflation, credit ratings and speculation",
  "3.3.6": "the terms of trade, its meaning and measurement and the factors that may affect the terms of trade, including commodity prices and production costs in trading partners",
  "3.3.7": "international competitiveness and the factors that may affect international competitiveness, including productivity, production costs, availability of natural resources, exchange rates and relative rates of inflation",
  "3.3.8": "the effect of movements in the terms of trade and the exchange rate, and changes in international competitiveness on the domestic macroeconomic goals and living standards",
  "4.1.1": "the need for aggregate demand policies, including monetary policy and budgetary policy in terms of stabilising the business cycle",
  "4.1.2": "sources of government revenue, including direct and indirect taxation; progressive, regressive and proportional taxes; and revenue from government businesses and the sale of government assets",
  "4.1.3": "types of government expenses, including government current and capital expenditure and transfer payments",
  "4.1.4": "the budget outcome: balanced, deficit or surplus",
  "4.1.5": "the underlying cash balance (budget outcome), including as a proportion of Gross Domestic Product (GDP)",
  "4.1.6": "methods of financing a deficit or utilising a surplus",
  "4.1.7": "the relationship between the budget outcome and the level of government (public) debt",
  "4.1.8": "the role of automatic stabilisers (cyclical component of the budget) in influencing aggregate demand and stabilising the business cycle",
  "4.1.9": "the role of discretionary stabilisers (structural component of the budget) in influencing aggregate demand and stabilising the business cycle",
  "4.1.10": "the effect of automatic and discretionary changes in the budget on the budget outcome and government (public) debt",
  "4.1.11": "the stance of budgetary policy: expansionary or contractionary",
  "4.1.12": "the effect of the budgetary policy stance and budgetary initiatives over the past two years and their likely effect on the achievement of the domestic macroeconomic goals and living standards",
  "4.1.13": "the strengths and weaknesses of using budgetary policy to affect aggregate demand and influence the achievement of the domestic macroeconomic goals and living standards",
  "4.1.14": "the role of the RBA with respect to monetary policy as outlined in its charter",
  "4.1.15": "conventional monetary policy (cash rate target) and how it affects interest rates",
  "4.1.16": "one example of the operation of an unconventional monetary policy tool from the past two years",
  "4.1.17": "transmission mechanism of monetary policy and its effect on the level of aggregate demand, including the four channels of savings and investment, cash-flow, exchange rate, and asset prices and wealth",
  "4.1.18": "the stance of monetary policy: expansionary (accommodative), contractionary (restrictive) or neutral",
  "4.1.19": "the stance of monetary policy over the past two years and its likely effect on the achievement of the domestic macroeconomic goals and living standards",
  "4.1.20": "the strengths and weaknesses of using monetary policy to affect aggregate demand and influence the achievement of the domestic macroeconomic goals and living standards",
  "4.2.1": "the use of aggregate supply policies to complement aggregate demand policies in promoting non-inflationary economic growth over time",
  "4.2.2": "the operation of aggregate supply policies in improving supply-side conditions through their impact on the quantity and quality of the factors of production, the costs of production and productivity, and the effect on Australia’s international competitiveness, productive capacity and aggregate supply",
  "4.2.3": "how one of the following budgetary policies is designed to affect aggregate supply, Australia’s international competitiveness, the achievement of domestic macroeconomic goals, and living standards:training and education ✓research and developmentsubsidiesinfrastructuretax reform",
  "4.2.4": "the effect of skilled immigration policy on population, productivity and participation and the subsequent effect on productive capacity, aggregate supply, international competitiveness, the achievement of domestic macroeconomic goals, and living standards",
  "4.2.5": "trade liberalisation and its short-term and long-term effects on Australia’s international competitiveness, the allocation of resources, aggregate supply, and the domestic macroeconomic goals and living standards",
  "4.2.6": "one market-based environmental policy and its short-term and long-term effects on aggregate supply, intertemporal efficiency and living standards",
};
